### ISSUE TITLE
Support net standard 2.0

### ISSUE THREAD

**Issue by mgrandi** [PivotalServicesOss/moq_datareader#10]
https://www.nuget.org/packages/Moq supports net standard 2.0, but this package seems to only support net standard 2.1 as the lower bound

i don't see any API usage that would cause an issue with lowering the minimum version

**Comment by alfusinigoj** [comment]
@mgrandi you are right, I shall add the change and get in a newer version. thank you for letting me know.

**Comment by alfusinigoj** [comment]
Released [v2.0.2](https://www.nuget.org/packages/PivotalServices.MoqExtensions.DataReader) , resolved this issue. Closing this issue. Thanks for the feedback @mgrandi

**Comment by mgrandi** [comment]
Wow! Thanks for tackling this so quickly!
