### ISSUE TITLE
MockDataReader confusing not supported exception for nullables

### ISSUE THREAD

**Issue by ShadowDIO** [PivotalServicesOss/moq_datareader#8]
I started using your project for testing some DataReaders and misconfigured the MockDataColumns from the MockDataTable for nullable fields, adding the nullable type to the second parameter, when trying to run the tests, I simply got a NotSupportedException Nullable'1; after cloning your code I found that while nullable types are not supported for types, they are when defining the columns, I added a case to spot these scenarios and added a message to the exception thrown indicating to use the third parameter in the MockDataColumn for those cases. I want to commit the correction but it says my user has no permissions for this repo. Can I make that change?

**Comment by alfusinigoj** [comment]
Can you please create a PR and let me know?

**Comment by alfusinigoj** [comment]
So that I can review and merge it to the package.

**Comment by ShadowDIO** [comment]
I can't commit my branch since I don't have permissions, I see an invitation to collaborate but it is saying that it no longer exists.

**Comment by alfusinigoj** [comment]
For now, can you please try creating a fork and create a PR from there?

Meanwhile I ll see what went wrong with the invite.

—
Regards,
Alfus Jaganathan<https://www.alfusjaganathan.com>
Github<https://github.com/alfusinigoj> | LinkedIn<https://www.linkedin.com/in/alfusinigojaganathan/> | Twitter<https://twitter.com/AlfusinigoJ><https://twitter.com/AlfusinigoJ>
(Sent from mobile)
<https://aka.ms/o0ukef>
________________________________

**Comment by alfusinigoj** [comment]
Released v2.0.1, based on your PR #9 https://www.nuget.org/packages/PivotalServices.MoqExtensions.DataReader/
